# Change these first
owner: thesagor # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Thought Leadership
    url: https://thoughtleadership.biz
  - name: Sitetrax
    url: https://sitetrax.io
  - name: Netarus
    url: https://netarus.com
  - name: HoistCam
    url: https://hoistcam.com
  - name: Traxa
    url: https://traxa.io
  - name: Machut
    url: https://www.machut.com
  - name: TrackMyContainer
    url: https://trackmycontainer.io
  - name: Sitetrax Customer
    url: https://customer.sitetrax.io
  - name: HoistCam Customer
    url: https://customer.hoistcam.com
  - name: Gorurhaat 
    url: https://gorurhaat.com
    
   # name: IPv6 test
   # url: forwardemail.net
   # port: 80
   # check: "tcp-ping"
   # ipv6: true

status-website:
  cname: status.devscode.tech # Custom domain name
  baseUrl: status.devscode.tech/
  logoUrl: https://raw.githubusercontent.com/thesagor/navbar/master/digisunnah.png
  name: DiGiSUnnah
  introTitle: "This is the open-source uptime monitor and status page, powered entirely by **Sagor Ahmed**."
  introMessage: Welcome to the status page, built specifically for my valued client, Chris Machut. This platform provides real-time monitoring data, pulled directly from our GitHub repository. 
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/thesagor
    - title: Contact
      href: https://www.fiverr.com/users/wordpress_sagor/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
